ipams/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# import debug_toolbar
from django.views.static import serve
from ipams import settings

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('', include('records.urls')),
    path('account/', include('accounts.urls')),
    path('notifications/', include('notifications.urls')),
    path('admin/', admin.site.urls),
    # path('__debug__/', include(debug_toolbar.urls)),
]

records/urls.py
from django.conf.urls.static import static
from django.urls import path

from ipams import settings
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='records-index'),
    path('dashboard', views.Dashboard.as_view(), name='records-dashboard'),
    path('dashboard/manage/documents', views.ViewManageDocuments.as_view(), name='dashboard-manage-documents'),
    path('dashboard/manage/documents/record/<int:record_id>', views.ViewManageDocumentsRecord.as_view(), name='dashboard-manage-documents-record'),
    path('dashboard/manage/records', views.ViewManageRecords.as_view(), name='dashboard-manage-records'),
    path('dashboard/logs', views.LogsView.as_view(), name='dashboard-logs'),
    path('dashboard/manage/records/<int:record_id>', views.DashboardManageRecord.as_view(), name='dashboard-manage-record'),
    path('dashboard/manage/accounts', views.DashboardManageAccounts.as_view(), name='dashboard-manage-accounts'),
    path('dashboard/logs/record/<int:record_id>', views.DashboardLogsRecordView.as_view(), name='dashboard-logs-record'),
    path('record/<int:record_id>', views.ViewRecord.as_view(), name='records-view'),
    path('record/myrecords/<int:record_id>', views.MyRecordView.as_view(), name='records-myrecords-view'),
    path('record/pending/<int:record_id>', views.PendingRecordView.as_view(), name='records-pending-view'),
    path('record/approved/<int:record_id>', views.ApprovedRecordView.as_view(), name='records-approved-view'),
    path('record/declined/<int:record_id>', views.DeclinedRecordView.as_view(), name='records-declined-view'),
    path('add/', views.Add.as_view(), name='records-add'),
    path('add/research/<int:research_record_id>', views.AddResearch.as_view(), name='records-add-research'),
    path('edit/<int:record_id>', views.Edit.as_view(), name='records-edit'),
    path('uploadexcel/', views.ParseExcel.as_view(), name='records-upload'),
    path('downloadformat/', views.download_format, name='records-download-format'),
    path('download/abstract/<int:record_id>', views.download_abstract, name='records-download-abstract'),
    path('download/document/<int:record_upload_id>', views.download_document, name='records-download-document'),
    path('records/user/', views.MyRecordsView.as_view(), name='records-myrecords'),
    path('records/pending/', views.PendingRecordsView.as_view(), name='records-pending'),
    path('records/approved/', views.ApprovedRecordsView.as_view(), name='records-approved'),
    path('records/declined/', views.DeclinedRecordsView.as_view(), name='records-declined'),

    path('lockout', views.LockoutPage.as_view(), name='lockout-page'),
    path('dashboard/reset/accounts', views.LockedAccountsView.as_view(), name='reset-accounts'),
    path('delete/requests', views.get_all_delete_requests, name="all-delete-requests"),
    path('record/pending/delete/request/<int:record_id>', views.PendingDeleteRecordsView.as_view(), name='pending-delete-view'),
    path('download/requests', views.get_all_download_requests, name="all-download-requests"),
    path('approved/download/request', views.approved_download_requests, name="download-request"),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/models.py
from django.db import models
from ckeditor.fields import RichTextField
import datetime 
from django.core.validators import MaxValueValidator, MinValueValidator

class Classification(models.Model):
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class PSCEDClassification(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class PublicationLevel(models.Model):
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class AuthorRole(models.Model):
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ConferenceLevel(models.Model):
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class BudgetType(models.Model):
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class CollaborationType(models.Model):
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class RecordType(models.Model): 
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Record(models.Model):
    title = models.CharField(max_length=100)
    year_accomplished = models.CharField(max_length=30) #Year Started
    year_completed = models.CharField(max_length=30, default='', null=True, blank=True)
    abstract = RichTextField()
    classification = models.ForeignKey(Classification, on_delete=models.DO_NOTHING)
    psced_classification = models.ForeignKey(PSCEDClassification, on_delete=models.DO_NOTHING)

    # abstract_filename and abstract_filesize is supposed to be use when there will be a cloud storage
    # to be used in saving the files to prevent uploading the
    # file itself to the default django storage
    abstract_filename = models.CharField(max_length=150, default='', null=True, blank=True)
    abstract_filesize = models.IntegerField(default=0, null=True, blank=True)

    abstract_file = models.FileField(upload_to='abstract/', default='', null=True, blank=True)  # WHOLE RESEARCH PAPER
    is_ip = models.BooleanField(default=False)
    for_commercialization = models.BooleanField(default=False)
    community_extension = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    adviser = models.ForeignKey('accounts.User', on_delete=models.DO_NOTHING, null=True, blank=True)
    record_type = models.ForeignKey(RecordType, on_delete=models.DO_NOTHING, null=True, blank=True, default=3)
    representative = models.CharField(max_length=100)
    code = models.CharField(max_length=100, default='', null=True, blank=True)
    is_marked = models.BooleanField(default=False) # marked for deletion
    reason = models.TextField() # reason for deleting the record

    def __str__(self):
        return self.title

class ResearchRecord(models.Model):
    proposal = models.ForeignKey(Record, on_delete=models.CASCADE, related_name='proposal')
    research = models.ForeignKey(Record, on_delete=models.SET_NULL, related_name='research', null=True, blank=True)

    # def __str__(self):
    #     return self.research

class CheckedRecord(models.Model):
    record = models.ForeignKey(Record, on_delete=models.CASCADE)
    checked_by = models.ForeignKey('accounts.User', on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=100)
    comment = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.record.title

class Publication(models.Model):
    name = models.CharField(max_length=200, default='', null=True, blank=True)
    isbn = models.CharField(max_length=50, default='', null=True, blank=True)
    issn = models.CharField(max_length=50, default='', null=True, blank=True)
    isi = models.CharField(max_length=50, default='', null=True, blank=True)
    year_published = models.CharField(max_length=50, default='', null=True, blank=True)
    publication_level = models.ForeignKey(PublicationLevel, on_delete=models.DO_NOTHING, null=True, blank=True)
    record = models.OneToOneField(Record, on_delete=models.CASCADE, primary_key=True, default=None)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=100)
    record = models.ForeignKey(Record, on_delete=models.CASCADE)
    author_role = models.ForeignKey(AuthorRole, on_delete=models.DO_NOTHING)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Conference(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    venue = models.CharField(max_length=100)
    conference_level = models.ForeignKey(ConferenceLevel, on_delete=models.DO_NOTHING)
    record = models.ForeignKey(Record, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Budget(models.Model):
    budget_allocation = models.FloatField()
    funding_source = models.CharField(max_length=100)
    budget_type = models.ForeignKey(BudgetType, on_delete=models.DO_NOTHING)
    record = models.ForeignKey(Record, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.funding_source

class Collaboration(models.Model):
    industry = models.CharField(max_length=100)
    institution = models.CharField(max_length=100)
    collaboration_type = models.ForeignKey(CollaborationType, on_delete=models.DO_NOTHING)
    record = models.ForeignKey(Record, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.institution

class Upload(models.Model):
    name = models.CharField(max_length=100)
    record_type = models.ForeignKey(RecordType, default=1, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class RecordUploadStatus(models.Model):
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class RecordUpload(models.Model):
    file = models.FileField(upload_to='documents/', null=True, blank=True)

    # filename is supposed to be use when there will be a cloud storage
    # to be used in saving the files to prevent uploading the
    # file itself to the default django storage
    filename = models.CharField(max_length=150, default='')

    upload = models.ForeignKey(Upload, on_delete=models.CASCADE)
    record = models.ForeignKey(Record, on_delete=models.CASCADE)
    record_upload_status = models.ForeignKey(RecordUploadStatus, on_delete=models.CASCADE)
    is_ip = models.BooleanField(default=False)
    for_commercialization = models.BooleanField(default=False)
    date_uploaded = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.record.title + " - " + self.upload.name

class CheckedUpload(models.Model):
    comment = models.TextField()
    checked_by = models.ForeignKey('accounts.User', on_delete=models.DO_NOTHING)
    record_upload = models.ForeignKey(RecordUpload, on_delete=models.CASCADE)
    date_checked = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.checked_by.username


class RecordDownloadRequest(models.Model):
    sent_by = models.ForeignKey('accounts.User', on_delete=models.CASCADE, null=True, blank=True)
    record = models.ForeignKey(Record, on_delete=models.CASCADE)
    is_marked = models.BooleanField(default=False) # if request is approved
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sent_by.username

records/templates/records/home_navbar.html
<nav>
    <div class="nav nav-tabs" role="tablist">
        <a id="nav-home-menu-1" class="col-lg-auto nav-item nav-link nav-main active" data-toggle="tab" href="#nav-home-landing" role="tab"><i class="fa fa-home fa-md"></i></a>
        <a id="nav-home-menu-2" class="col-lg-auto col-lg-auto nav-item nav-link nav-main" data-toggle="tab" href="#nav-home-records" role="tab"><i class="fa fa-book fa-md"></i> RECORDS</a>
        {% if user.role.id > 2 %}
        <a id="nav-home-menu-3" class="col-lg-auto nav-item nav-link nav-main" data-toggle="tab" href="#nav-home-accounts" role="tab"><i class="fa fa-user fa-md"></i> ACCOUNTS</a>
        <a id="nav-home-menu-4" class="col-lg-auto nav-item nav-link nav-main" data-toggle="tab" href="#nav-home-upload" role="tab"><i class="fa fa-upload fa-md"></i> UPLOAD</a>
        {% endif %}
    </div>
</nav>

records/templates/records/lockout_page.html
{% extends 'ipams/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        Locked out due to too many login failures. Max limit has been reached. Please contact the admin to reset account.
        <br><br>
        <a href="{% url 'records-index' %}" style="font-size: 18px; font-weight: bold;">Go back to Homepage</a>
    </div>
{% endblock %}

records/templates/records/record_navbar.html
<nav>
	<div class="nav nav-tabs" role="tablist" id="classification-nav">
		<a class="nav-item nav-link nav-main title-and-abstract active d-none d-lg-block" data-toggle="tab" href="#nav-title-and-abstract" role="tab" id="nav-item-1" onclick="classificationClick('1')">Title and Abstract</a>
		<a class="nav-item nav-link nav-main author d-none d-lg-block" data-toggle="tab" href="#nav-authors-and-categories" role="tab" id="nav-item-2" onclick="classificationClick('2')">Authors and Categories</a>
		<a class="nav-item nav-link nav-main conference d-none d-lg-block" data-toggle="tab" href="#nav-conference" role="tab" id="nav-item-3" onclick="classificationClick('3')">Conference</a>
		<a class="nav-item nav-link nav-main publication d-none d-lg-block" data-toggle="tab" href="#nav-publication" role="tab" id="nav-item-4" onclick="classificationClick('4')">Publication</a>
		<a class="nav-item nav-link nav-main budget d-none d-lg-block" data-toggle="tab" href="#nav-budget" role="tab" id="nav-item-5" onclick="classificationClick(5)">Budget</a>
		<a class="nav-item nav-link nav-main collaboration d-none d-lg-block" data-toggle="tab" href="#nav-collaboration" role="tab" id="nav-item-6" onclick="classificationClick('6')">Collaboration</a>
		{% if user.role.id > 2 or is_owner %}
		<a class="nav-item nav-link nav-main uploads d-none d-lg-block" data-toggle="tab" href="#nav-uploads" role="tab" id="nav-item-7" onclick="classificationClick('7')">Uploads</a>
		{% endif %}
	</div>
</nav>

records/templates/records/update.html
{% extends 'ipams/base.html' %}

{% block footer %}
	<script>
		var authorCount = 1;
		var conferenceCount = 1;
		var budgetCount = 1;
		var collaborationCount = 1;

		function removeAuthor(id=0){
			authorCount--;
			$("#author-"+id).remove();
		}

		function removeConference(id=0){
			conferenceCount--;
			$("#conference-"+id).remove();
		}

		function removeBudget(id=0){
			budgetCount--;
			$("#budget-"+id).remove();
		}

		function removeCollaboration(id=0){
			collaborationCount--;
			$("#collaboration-"+id).remove();
		}

		$("#add-author-btn").on("click",function(){
			authorCount++;
			$("#author-rows").append('<div class="row" id="author-'+authorCount+'"><div class="col-7"><input name="author_names[]" placeholder="Name" class="form-control" type="text"></div><div class="col-3"><select name="author_roles[]" class="form-control"> {% for author_role in author_roles %}<option value="{{ author_role.pk }}">{{ author_role.name }}</option> {% endfor %} </select></div><div class="col-2"><button class="btn btn-danger" type="button" onclick="removeAuthor('+authorCount+')">REMOVE</button></div></div>');
		});

		$("#add-conference-btn").on("click",function(){
			conferenceCount++;
			$("#conference-rows").append('<div class="row" id="conference-'+conferenceCount+'"><div class="col-2"><select name="conference_levels[]" class="form-control"> {% for conference_level in conference_levels %} <option value="{{ conference_level.pk }}">{{ conference_level.name }}</option> {% endfor %} </select></div><div class="col-3"><input type="text" placeholder="Title" name="conference_titles[]" class="form-control"></div><div class="col-2"><input type="date" name="conference_dates[]" class="form-control"></div><div class="col-3"><input type="text" placeholder="Venue" name="conference_venues[]" class="form-control"></div><div class="col-2"><button class="btn btn-danger" type="button" onclick="removeConference('+conferenceCount+')">REMOVE</button></div></div>');
		});

		$("#add-budget-btn").on("click",function(){
			budgetCount++;
			$("#budget-rows").append('<div class="row" id="budget-'+budgetCount+'"><div class="col-2"><select name="budget_types[]" class="form-control"> {% for budget_type in budget_types %} <option value="{{ budget_type.pk }}">{{ budget_type.name }}</option> {% endfor %} </select></div><div class="col-4"><input type="number" name="budget_allocations[]" placeholder="Budget Allocation" class="form-control"></div><div class="col-4"><input type="text" name="funding_sources[]" placeholder="Funding Source" class="form-control"></div><div class="col-2"><button class="btn btn-danger" type="button" onclick="removeBudget('+budgetCount+')">REMOVE</button></div></div>');
		});

		$("#add-collaboration-btn").on("click",function(){
			collaborationCount++;
			$("#collaboration-rows").append('<div class="row" id="collaboration-'+collaborationCount+'"><div class="col-4"><input type="text" name="industries[]" class="form-control" placeholder="Other Industry"></div><div class="col-4"><input type="text" name="institutions[]" class="form-control" placeholder="Institution"></div><div class="col-2"><select name="collaboration_types[]" class="form-control"> {% for collaboration_type in collaboration_types %} <option value="{{ collaboration_type.pk }}">{{ collaboration_type.name }}</option> {% endfor %} </select></div><div class="col-2"><button class="btn btn-danger" type="button" onclick="removeCollaboration('+collaborationCount+')">REMOVE</button></div></div>');
		});

		/*$("#btn-save").on("click",function(){
			$.ajax({
				headers: {
                    'X-CSRF-Token': $("meta[name='csrf-token']").attr("content")
                },
				url: $("#form-record").attr("action"),
				type: $("#form-record").attr("method"),
				data: $("#form-record").serialize(),
				dataType: "json",
				success: function(data){
					alert("success ");
				},
				error: function(data){
					alert("error");
				},
			});
		});*/

	</script>
{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12" style="margin-top:30px; margin-bottom:30px">
				<a href="{% url 'records-index' %}">Records</a> / <a href="{% url 'records-view' record_id=record.pk %}">{{ record.title }}</a> / Update
			</div>
		</div>
		<form method="post" action="{% url 'records-add' %}" id="form-record">
			{% csrf_token %}
<!--------------------------------------TITLE AND ABSTRACT---------------------------------------------------->
			<section id="title-and-abstract">
				<div class="row">
					<div class="col-12">
						<h3>TITLE AND ABSTRACT</h3>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<input type="text" name="title" class="form-control" placeholder="title" value="{{ record.title }}" required>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<input type="text" name="year_accomplished" class="form-control" placeholder="year accomplished" value="{{ record.year_accomplished }}">
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<input type="text" name="abstract" class="form-control" placeholder="abstract" value="{{ record.abstract }}">
					</div>
				</div>
			</section>
<!--------------------------------------AUTHORS AND CATEGORIES---------------------------------------------------->
			<section id="authors-and-categories">
				<div class="row">
					<div class="col-12">
						<h3 style="margin-top: 30px">AUTHORS AND CATEGORIES</h3>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<button class="btn btn-primary" type="button" id="add-author-btn">ADD AUTHOR</button>
					</div>
				</div>
				<div id="author-rows">
					{% for author in record.author_set.all %}
					<div class="row" id="author-{{ author.pk }}">
						<div class="col-7">
							<input name="author_names[]" placeholder="Name" class="form-control" type="text" value="{{ author.name }}" required>
						</div>
						<div class="col-3">
							<select name="author_roles[]" class="form-control">
								{% for author_role in author_roles %}
									<option value="{{ author_role.pk }}" {% if author.author_role.pk == author_role.pk %} selected {% endif %}>{{ author_role.name }}</option>
								{% endfor %}
							</select>
						</div>
						<div class="col-2">
							<button class="btn btn-danger" type="button" onclick="removeAuthor(1)">REMOVE</button>
						</div>
					</div>
					{% endfor %}
				</div>
				<div class="row">
					<div class="col-12">
						<select name="classification" class="form-control">
							{% for classification in classifications %}
								<option value="{{ classification.pk }}" {% if record.classification.pk == classification.pk %} selected {% endif %}>{{ classification.name }}</option>
							{% endfor %}
						</select>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<select name="psced_classification" class="form-control">
							{% for psced_classification in psced_classifications %}
								<option value="{{ psced_classification.pk }}" {% if record.psced_classification.pk == psced_classification.pk %} selected {% endif %}>{{ psced_classification.name }}</option>
							{% endfor %}
						</select>
					</div>
				</div>
			</section>
<!--------------------------------------CONFERENCE---------------------------------------------------->
			<section id="conference">
				<div class="row">
					<div class="col-12">
						<h3 style="margin-top: 30px">CONFERENCE</h3>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<button class="btn btn-primary" type="button" id="add-conference-btn">ADD CONFERENCE</button>
					</div>
				</div>
				<div id="conference-rows">
					{% for conference in record.conference_set.all %}
					<div class="row" id="conference-1">
						<div class="col-2">
							<select name="conference_levels[]" class="form-control">
								{% for conference_level in conference_levels %}
									<option value="{{ conference_level.pk }}" {% if conference.conference_level.pk == conference_level.pk %} selected {% endif %}>{{ conference_level.name }}</option>
								{% endfor %}
							</select>
						</div>
						<div class="col-3">
							<input type="text" placeholder="Title" name="conference_titles[]" class="form-control" value="{{ conference.title }}" required>
						</div>
						<div class="col-2">
							<input type="date" name="conference_dates[]" class="form-control" value="{{ conference.date|date:'Y-m-d' }}" required>
						</div>
						<div class="col-3">
							<input type="text" placeholder="Venue" name="conference_venues[]" class="form-control" value="{{ conference.venue }}">
						</div>
						<div class="col-2">
							<button class="btn btn-danger" type="button" onclick="removeConference(1)">REMOVE</button>
						</div>
					</div>
					{% endfor %}
				</div>
			</section>
<!--------------------------------------PUBLICATION---------------------------------------------------->
			<section id="publication">
				<div class="row">
					<div class="col-12">
						<h3 style="margin-top: 30px">PUBLICATION</h3>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<input type="text" class="form-control" name="publication_name" placeholder="Name" value="{{ record.publication.name }}">
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<input type="text" class="form-control" name="isbn" placeholder="ISBN" value="{{ record.publication.isbn }}">
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<input type="text" class="form-control" name="issn" placeholder="ISSN" value="{{ record.publication.issn }}">
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<input type="text" class="form-control" name="isi" placeholder="ISI" value="{{ record.publication.isi }}">
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<select name="publication_level" class="form-control">
							{% for publication_level in publication_levels %}
								<option value="{{ publication_level.pk }}" {% if record.publication.publication_level.pk == publication_level.pk %} selected {% endif %}>{{ publication_level.name }}</option>
							{% endfor %}
						</select>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<input type="text" class="form-control" name="year_published" placeholder="Year Published" value="{{ record.publication.year_published }}">
					</div>
				</div>
			</section>
<!--------------------------------------BUDGET---------------------------------------------------->
			<section id="budget">
				<div class="row">
					<div class="col-12">
						<h3 style="margin-top: 30px">BUDGET</h3>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<button class="btn btn-primary" type="button" id="add-budget-btn">ADD BUDGET</button>
					</div>
				</div>
				<div id="budget-rows">
					{% for budget in record.budget_set.all %}
					<div class="row" id="budget-1">
						<div class="col-2">
							<select name="budget_types[]" class="form-control">
								{% for budget_type in budget_types %}
									<option value="{{ budget_type.pk }}" {% if budget.budget_type.pk == budget_type.pk %} selected {% endif %}>{{ budget_type.name }}</option>
								{% endfor %}
							</select>
						</div>
						<div class="col-4">
							<input type="number" name="budget_allocations[]" placeholder="Budget Allocation" class="form-control" value="{{ budget.budget_allocation }}" required>
						</div>
						<div class="col-4">
							<input type="text" name="funding_sources[]" placeholder="Funding Source" class="form-control" value="{{ budget.funding_source }}" required>
						</div>
						<div class="col-2">
							<button class="btn btn-danger" type="button" onclick="removeBudget(1)">REMOVE</button>
						</div>
					</div>
					{% endfor %}
				</div>
			</section>
<!--------------------------------------COLLABORATION---------------------------------------------------->
			<section id="collaboration">
				<div class="row">
					<div class="col-12">
						<h3 style="margin-top: 30px">COLLABORATION</h3>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<button class="btn btn-primary" type="button" id="add-collaboration-btn">ADD COLLABORATION</button>
					</div>
				</div>
				<div id="collaboration-rows">
					{% for collaboration in record.collaboration_set.all %}
					<div class="row" id="collaboration-1">
						<div class="col-4">
							<input type="text" name="industries[]" class="form-control" placeholder="Other Industry" value="{{ collaboration.industry }}">
						</div>
						<div class="col-4">
							<input type="text" name="institutions[]" class="form-control" placeholder="Institution" value="{{ collaboration.institution }}" required>
						</div>
						<div class="col-2">
							<select name="collaboration_types[]" class="form-control">
								{% for collaboration_type in collaboration_types %}
									<option value="{{ collaboration_type.pk }}" {% if collaboration.collaboration_type.pk == collaboration_type.pk %} selected {% endif %}>{{ collaboration_type.name }}</option>
								{% endfor %}
							</select>
						</div>
						<div class="col-2">
							<button class="btn btn-danger" type="button" onclick="removeCollaboration(1)">REMOVE</button>
						</div>
					</div>
					{% endfor %}
				</div>
			</section>

			<div class="row" style="margin-bottom:30px; margin-top:30px">
				<div class="col-12 d-flex justify-content-end">
					<a type="button" href="{% url 'records-index' %}" class="btn btn-warning" id="btn-back">Back to Records</a>&nbsp;
					<button type="submit" class="btn btn-success" id="btn-save">Update</button>
				</div>
			</div>
		</form>
	</div>
{% endblock %}